<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true"
    CodeFile="Default.aspx.cs" Inherits="_Default" %>

<%@ Register Assembly="RepositoryDataSource" Namespace="Aspx.WebControls" TagPrefix="x" %>

<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
	<asp:GridView ID="GridView1" runat="server"
		Width="600" 
		DataSourceID="DataSource1" 
		PageSize="3"
		AllowPaging="true"
		AllowSorting="true"
		DataKeyNames="id"
		AutoGenerateColumns="false">
		<Columns>
			<asp:TemplateField HeaderText="ID" SortExpression="ID">
				<ItemTemplate>  
					<asp:Label ID="ID" runat="server" Text='<%# Bind("ID") %>'></asp:Label>  
				</ItemTemplate>  
			</asp:TemplateField>
			<asp:TemplateField HeaderText="Name" SortExpression="Name">
				<ItemTemplate>  
                    <asp:Label ID="Name" runat="server" Text='<%# Bind("Name") %>'></asp:Label>  
                </ItemTemplate>  
			</asp:TemplateField>
			<asp:TemplateField HeaderText="Stock" SortExpression="Stock, ID Desc">
				<ItemTemplate>  
					<asp:Label ID="Stock" runat="server" Text='<%# Bind("Stock") %>'></asp:Label>  
				</ItemTemplate>  
			</asp:TemplateField>
		</Columns>
	</asp:GridView>
	<br /><br />
	<asp:DetailsView ID="DetailsView1" runat="server"
		Width="600" 
		DataSourceID="DataSource1"
		AllowPaging="true"
		AutoGenerateDeleteButton="true"
		AutoGenerateEditButton="true"
		AutoGenerateInsertButton="true"
		AutoGenerateRows="true"
		DataKeyNames="id">
	</asp:DetailsView>
	<x:RepositoryDataSource
		ID="DataSource1" runat="server"
		Target="RepositoryDataSource.Demo.Data.DataContext.ProductRepository"
		OnDataBinding="DataSource_DataBinding"
		OnDeleted="DataSource_Deleted"
		OnDeleting="DataSource_Deleting"
		OnDisposed="DataSource_Disposed"
		OnInit="DataSource_Init"
		OnInserted="DataSource_Inserted"
		OnInserting="DataSource_Inserting"
		OnLoad="DataSource_Load"
		OnObjectCreated="DataSource_ObjectCreated"
		OnObjectCreating="DataSource_ObjectCreating"
		OnObjectDisposing="DataSource_ObjectDisposing"
		OnPreRender="DataSource_PreRender"
		OnSelected="DataSource_Selected"
		OnSelecting="DataSource_Selecting"
		OnUnload="DataSource_Unload"
		OnUpdated="DataSource_Updated"
		OnUpdating="DataSource_Updating"
		SelectMethod="GetAll"
		InsertMethod="InsertCustomer"
		UpdateMethod="UpdateCustomer"
		DeleteMethod="DeleteCustomer">
	</x:RepositoryDataSource>
</asp:Content>
